### ISSUE TITLE
[Bug]: Cannot read symlinked files?

### ISSUE THREAD

**Issue by halostatue** [KnodesCommunity/typedoc-plugins#180]
### Plugin

@knodes/typedoc-plugin-pages

### Typedoc plugin(s) version(s)

@knodes/typedoc-plugin-pages 0.23.1

### Typedoc version

0.23.12

### Describe the problem

I’m running typedoc in `<package_path>/ts`. I have a symlink `spec.md -> ../spec/README.md` and the following in my `typedoc.js` configuration:

```javascript
module.exports = {
  // …
  pluginPages: {
    pages: [
      { title: 'Spec', children: [{ title: 'Specification', source: './spec.md' }] },
    ],
  },
}
```

When I run with this config, I get the following (elided):

```
Error: Could not locate page for "mypackage - v1.0.0" ⇥ "My Documentation" ⇥ "Specification"
…
  [cause]: Error: Resolved file "<package_path>/ts/pages/spec.md" does not exists
```

If I change the source reference from `./spec.md` to either `../spec/README.md` or `../ts/spec.md` it works just fine.

### What did you expected ?

I expected that documentation generation would work.

**Comment by GerkinDev** [comment]
Hi,

That's unfortunate. Which OS are you using ? I'll try to create a repro

**Comment by halostatue** [comment]
macOS.

I’m having some other issues (like, how I manage to make documentation that isn’t one giant single page, because there’s a *lot* of documentation that needs to be present), but it looks like that’s more a problem with Typedoc and perhaps how this plugin works with `expand` strategy. Not entirely sure, and it‘s my first time using Typedoc in anger and my first time using this plug-in at all.

I’m far more comfortable with rdoc (Ruby) and exdoc (Elixir) where extra files are considered par for the course.

As a side issue, it would be *nice* if `{ title: … }` were optional, because when I *did* get the code working with the relative paths (it’s not *directly* symlink related, but it is a little weird that './spec.md' doesn’t work), I got both `title: …` *and* the generated `<h1>` of the markdown (because each of my documents is intended to be a *page*).

**Comment by GerkinDev** [comment]
There's an almost stable branch (I hope to merge soon) that would solve your issue. It would expose several ways of declaring your pages, one allowing to use glob matches to match against, for example, `CHANGELOG.md` or `README.md` files, and another that will load automatically all pages in a given folder, extracting infos such as the title from the front matter (just like Jekyll).

With this new format, I'll have more flexibility to add other loaders to better match some cases like the one you describe.

**Comment by GerkinDev** [comment]
I'm aware that the current declaration format is super verbose, and I'm sorry about this. It is a legacy from the previous unmaintained plugin this one is a fork of (as mentioned in the documentation). I do my best on my free time to improve it and make it as convenient as possible. But please take into consideration it's a side project.

**Comment by halostatue** [comment]
I’ll see if I can give you a small repro in a week or so; I’ve been working on the documentation and testing side of a three-language monorepo for the last month off and on, and I’m reaching the exhausting end of it all.

I’m likely to punt on this for a while and just make sure that the typedoc is complete as can be and then make sure that all of the extras are in the actual *documentation* site that I make after initial package launch. I’ll probably move the `typedoc-pages` plugin work to a branch to come back to when I have energy again.

**Comment by GerkinDev** [comment]
Hey there, just pinging to see if you're still alive (I bet you do) and willing to post a repro. Would be nice for tests in the next release

**Comment by halostatue** [comment]
https://github.com/halostatue/typedoc-plugin-pages-180

This is a stripped-down version of the original repo.

**Comment by halostatue** [comment]
@GerkinDev Just a bump that I did provide a repro on this.

**Comment by GerkinDev** [comment]
Oh thank you, I'll make sure next release fix this

**Comment by GerkinDev** [comment]
I FINALLY have some bandwidth to take a look at this!

**Comment by GerkinDev** [comment]
Hi, so, as far as how the plugin works, there is no bug with symlink. The issue you're encountering is related to a default option, see the [default value of the `source` option](https://knodescommunity.github.io/typedoc-plugins/interfaces/_knodes_typedoc_plugin_pages.IPluginOptions.html#source).

Since you're using the default option, the plugin prepends `pages` to your pages links, as marked in the error message. I agree this is confusing & inconvenient; setting it to `null` should do the trick with relative pages. This option will be removed in a later release.

I added tests for symlinks nonetheless.

Hope it helps (even a bit late), cheers !
