### ISSUE TITLE
[Question]: The old style of linking to API docs from pages is broken

### ISSUE THREAD

**Issue by harishkswamy** [KnodesCommunity/typedoc-plugins#216]
### Plugin

@knodes/typedoc-plugin-pages

### Typedoc plugin(s) version(s)

0.23.1

### Typedoc version

0.23.8

### Describe the problem

In the old pages plugin (typedoc-plugin-pages@1.1.0) you could link to "objects" like classes etc in the API docs from pages like so `[[Clazz | clazz]]` but that seems like it is not supported anymore? Are there plans to support this in the future? If not, what is the suggested approach to specify these links besides providing the path to the generated docs like so `[clazz](../classes/framework_Clazz.Clazz.html)`.

### What did you expected ?

I expect `[[Clazz | clazz]]` to link to the `Clazz` in the generated docs

**Comment by GerkinDev** [comment]
Typedoc now uses `{@link Class}` notation. See the typedoc documentation: https://typedoc.org/tags/link/

**Comment by harishkswamy** [comment]
Thanks for getting back, I had tried the new link format and that wasn't working either with any of the entry point strategies.

For now I have a hack that resolves the issue, posting my solution here for posterity sake. If anyone has a better alternative please chime in. 

My project is a module and it only has the public API exported in the index file and that appears to be the issue because typedoc is unable to resolve links if I don't export all the types in every folder in the index file, so I ended up generating an index file in every folder before I run typedoc and I delete it after. That's the only way I could get it to work.

**Comment by GerkinDev** [comment]
Yeah indeed, typedoc collects symbols from your package entrypoint. This is somewhat understandable: API doc is mainly for 3rd party devs; why would they need to see internal symbols that are never used outside ? Using a secondary entrypoint for docs only can be indeed a good solution to be more explicit about what to put in documentation; yet, if user can see the symbol somehow from their code, like a typedef, they might be able to import it.

If you consider this issue not requiring more information, I invite you to close it. Thanks for the hint ;)
