### ISSUE TITLE
What does "Invalid pages configuration: could not find a workspace named "xxx"" means?

### ISSUE THREAD

**Issue by snird** [KnodesCommunity/typedoc-plugins#265]
### Plugin

@knodes/typedoc-plugin-pages

### Typedoc plugin(s) version(s)

0.23.1

### Typedoc version

0.23.21

### Describe the problem

I set up everything as documented, but kept getting this cryptic error message and couldn't figure out what it means nor did any search got something up

### What did you expected ?

better error

**Comment by GerkinDev** [comment]
Hi,
It means your configuration is somehow, invalid: you've set the `moduleRoot` flag on a page whose name is none of the name of your monorepo packages, or your project's name.
Please post your configuration so that I can help you.

**Comment by GerkinDev** [comment]
Closing for housekeeping purposes
