### ISSUE TITLE
[Feature]: Single codeblock showing multiple regions from a single file

### ISSUE THREAD

**Issue by shawninder** [KnodesCommunity/typedoc-plugins#291]
### Plugin

@knodes/typedoc-plugin-code-blocks

### What would you want ?

When embedding multiple regions of code from the same file into a markdown file, I would love to be able to provide the `@codeblock` tag with a list of regions and get them all shown in a single code block, with any gaps hinted at with `[…]`, or something like that.

## How it works now
What I do now instead looks like this:

```md
{@codeblock clients/unauthenticated.test-d.ts#import}

{@codeblock clients/unauthenticated.test-d.ts#instantiation}
```
It yields two code boxes, as you can see in the screenshots, under two labels:
- From `./examples/clients/unauthenticated.test-d.ts#3~7`
- From `./examples/clients/unauthenticated.test-d.ts#17~20`

![Screen Shot 2023-03-11 at 3 48 41 PM](https://user-images.githubusercontent.com/484730/224510978-0e31a648-1d55-430e-8ba0-11902890c800.jpg)

## In my wildest dreams
I wish I could use a single block like this:

```md
{@codeblock clients/unauthenticated.test-d.ts#import,instantiation}
```
This would produce a single label:
- From `./examples/clients/unauthenticated.test-d.ts#3~7&17~20`

and a single codeblock with the following contents (for comparison with screenshot above):
```ts
import HypothesisRestClient, {
  UnauthenticatedClient
} from 'hypothesis-rest'
// […]
const client = HypothesisRestClient()
expectType<UnauthenticatedClient>(client)
```

**Comment by GerkinDev** [comment]
This is actually supported, but undocummented. You can see an example use here:
https://knodescommunity.github.io/typedoc-plugins/modules/_knodes_typedoc_plugin_pages.html#example-configuration

Here is the code sample file:
https://github.com/KnodesCommunity/typedoc-plugins/blob/5711489e95f3f7a35c48c53b7927d13f567e5133/typedoc.js#L1-L66
Here is the page including the block parts:
https://github.com/KnodesCommunity/typedoc-plugins/blob/5711489e95f3f7a35c48c53b7927d13f567e5133/packages/plugin-pages/pages/readme-extras.md?plain=1#L5

The region tag in your block reference can be a glob pattern. For your use case, I suppose `{@codeblock clients/unauthenticated.test-d.ts#{import,instantiation}}` should do the trick. If it does not, it's a parsing problem with the closing `}`, I would then suggest you rename your blocks `example-1` & `example-2`, then use `{@codeblock clients/unauthenticated.test-d.ts#example-*}`.

This part is under tested, so I'd be happy to know if the 1st option works ;)

**Comment by shawninder** [comment]
Yeah, the closing `}` is a problem and (single/double/triple)-escaping doesn't help.

The glob thing does work though! Thanks :) I had seen this when scanning the docs but didn't think of it when this issue came up.

I do think the first option would have value if it worked though, to help with semantics in complex cases. Perhaps there is a different syntax not involving `}` that would work or could be made to work?

**Comment by GerkinDev** [comment]
Well, some time ago, I was working on a new version with plenty of fixes & improvements, and IIRC, that behavior was affected. I will re-check next time I open the project (super busy so I can't guarantee an ETA)

**Comment by GerkinDev** [comment]
Oh! Just thinking, you might be able to remove the wrapping curly altogether

Example :

```js
/**
 * some doc
 *
 * @codeblock example.d.ts#{foo,bar}
 */

**Comment by shawninder** [comment]
Hmm, good thought, but it doesn't exactly work.

I can import a single region despite omitting the wrapping brackets: `@codeblock example.d.ts#foo`
But when I try more regions, e.g. `@codeblock example.d.ts#{foo,bar}`, I get the following warnings and errors when running Typedoc:
> ./src/HypothesisRest.ts:142:26 - warning Encountered an unescaped open brace without an inline tag
> 
> 142     * @codeblock fixtures.ts#{connectionOptions,test}
> 
> ./src/HypothesisRest.ts:142:49 - warning Unmatched closing brace
> 
> 142     * @codeblock fixtures.ts#{connectionOptions,test}
> 
> error [@knodes/typedoc-plugin-code-blocks]: MarkdownCodeBlocks ⇒ In "src/HypothesisRest.ts:3:1 (in expansion of @codeblock)", failed to render code block from HypothesisRest: Error: Resolved file "/Users/shawn/git/shawninder/hypothesis-rest/src/examples/fixtures.ts" does not exists
> error Documentation could not be generated due to the errors above.

Of course, the file mentioned (/Users/shawn/git/shawninder/hypothesis-rest/src/examples/fixtures.ts) does in fact exist and I can import regions from it just fine if I do it one at a time…

In the final Typedoc output, my `@codeblock` instruction appears as plain text, and the wrapping curly brackets that I had avoided have been re-inserted for me: `{@codeblock fixtures.ts#{connectionOptions,test}}`

It's the same thing whether I put the instruction in a comment in code or in a Markdown file.

----

On a completely different subject, my browser is highlighting an English syntax error in the error messages I pasted above, lol:

> Resolved file "…" does not exists
should be
> Resolved file "…" does not exist
Notice the absence of a trailing "s" in the corrected version.

Anyways I thought I'd mention it real quick since the red squiggles are right there in my face, but clearly, this isn't a huge problem and is unrelated to our current discussion.

**Comment by GerkinDev** [comment]
Dang, I suppose Typedoc has *again* changed the parsing logic & behavior of tags.
The painful thing maintaining a Typedoc plugin is that their API is pretty messy and super unstable, and that's quite discouraging.

Thank you for the information. I expect many update chore next time I checkout latest typedoc version. Meh.

**Comment by shawninder** [comment]
I feel you. Well, don't do anything on my account, I have workarounds for my issues. It'll be a bonus if you fix this someday. Even as-is, I find this plugin very valuable because it lets me insert code into my docs which can be automatically tested and kept up-to-date.

**Comment by GerkinDev** [comment]
Actually, my bad; a regex was incorrect. A fix is pending
