### ISSUE TITLE
[Bug]: Importing regions with backticks (`) yields escaped backticks, breaking syntax highlighting

### ISSUE THREAD

**Issue by shawninder** [KnodesCommunity/typedoc-plugins#292]
### Plugin

@knodes/typedoc-plugin-code-blocks

### Typedoc plugin(s) version(s)

@knodes/typedoc-plugin-code-blocks@0.23.1

### Typedoc version

0.23.26

### Describe the problem

When importing the following region from a Typescript file:

```ts
// #region    test
const x = `hello`
const y = `world`
// #endregion test
```

I get the following output in my docs:
```ts
const x = \`hello\`
const y = \`world\`
```

Notice the backticks are now escaped. This breaks Typescript syntax, but also syntax highlighting in the Markdown render (as it is doing here in GitHub too).

### What did you expected ?

I was expecting unaltered code.

**Comment by GerkinDev** [comment]
Yes indeed, thanks for pointing it out. I will add tests for this.

**Comment by GerkinDev** [comment]
Hi,
Despite my efforts, I could not reproduce your issue from the latest version.
Could you please check if the latest version of the plugin solves the problem, or provide more context or even a minimal repro ?
Cheers ! :beers:

**Comment by shawninder** [comment]
Indeed, the problem seems to have disappeared, perhaps with the latest version of the code blocks plugin…? Or maybe with the new version of Typedoc? I am now using typedoc@0.23.28 and I reported the problem in 0.23.26…

Cheers!
