### ISSUE TITLE
[Bug]: @page reference doesn't seem to work

### ISSUE THREAD

**Issue by sstchur** [KnodesCommunity/typedoc-plugins#293]
### Plugin

@knodes/typedoc-plugin-code-blocks

### Typedoc plugin(s) version(s)

@knodes/typedoc-plugin-pages": "^0.23.1

### Typedoc version

typedoc": "^0.23.27

### Describe the problem

Created a simple structure like this:
```
pages
    |--- test.md
    |----test2.md
```

In my `typedoc.json`, I specified `"readme": "./pages/test.md"`

My plugin config is just:

```
    "pluginPages": {
      "pages": [
        { "title": "test", "source": "test.md" }
      ]
    }
```

When I run `typedoc`, I get:

```
error [@knodes/typedoc-plugin-pages]: MarkdownPagesLinks ⇒ In "pages/test.md:3:1 (in expansion of @page)", could not resolve page "./test2.md[Test" from reflection test
```

All I am trying to do is that I have a set of existing MD files (about 30 of them) which have explanations of core topics for the package.  They live under `./docs` but I changed that to `./pages` b/c it seems like that's what this plugin wants?

Those markdown (before) just had regular md links like `[Test](./test.md)`, but that style of link doesn't seem to work here.  

Any ideas what I'm doing wrong?

### What did you expected ?

I expect to be able to have my own existing markdown files, which reference other markdown files in the same folder.

**Comment by sstchur** [comment]
AH, I figured it out.

It needs to be:

test.md
`{@page ./test2.md Link to Test 2}`

config in typedoc.json
```
"pages": [
        { "title": "Test 2", "source": "test2.md" }
```

But this means I need one entry in pages for EVERY markdown file I already have?  And EVERY markdown file's links need to be updated to use the @page format?

This also means when I add a new markdown, I have to update "page" config in typedoc.json?

This feels pretty cumbersome.  Is there no way to bulk include all my markdowns?  Or have it scan or something?

**Comment by sstchur** [comment]
Sorry, one more comment:  Images referenced in markdown as in ![Some Alt Text](./img/my_image,png "An Optional Title")` also do not seems to work in the generated documentation.

Is there some equivalent directive like `@page` but for images?  I tried `@Img`, `@img`, `@Image`, and `@image`, but all are unrecognized.  How to reference images then?

**Comment by GerkinDev** [comment]
Hi, I don't know, images are out of the scope of this plugin.

Yeah the declarative format of `pages` is boring. I got a full rework of this system somewhere so that there is no need to modify the config when adding new pages, but I don't have the time to finalize & release it.
