### ISSUE TITLE
[Bug]: Code Blocks no longer work with typedoc 0.23.28

### ISSUE THREAD

**Issue by shawninder** [KnodesCommunity/typedoc-plugins#294]
### Plugin

@knodes/typedoc-plugin-code-blocks

### Typedoc plugin(s) version(s)

@knodes/typedoc-plugin-code-blocks@0.23.1

### Typedoc version

0.23.28

### Describe the problem

TypeDoc can't expand code blocks anymore. Instead, when I run `typedoc`, I get an error repeated many times (once for each `@codeblock`):

> error [@knodes/typedoc-plugin-code-blocks]: MarkdownCodeBlocks ⇒ In "FILE/PATH.md:r:c (in expansion of @codeblock)", failed to render code block from PAGE NAME: TypeError: Cannot read properties of undefined (reading 'GitHub').

The docs do build, but none of the `@codeblocks` are expanded and just appear in the docs as plain text.

I think the problem is that the plugin [imports `RepositoryType` from `typedoc`](https://github.com/KnodesCommunity/typedoc-plugins/blob/main/packages/plugin-code-blocks/src/output/markdown-code-blocks.ts#L6), but `typedoc` no longer exports such a member… This is just a guess, however, and I'm struggling to find an older version of Typedoc that does export `RepositoryType`…

### What did you expected ?

I was expecting the `@codeblocks` to be expanded correctly in the docs, as was the case with older versions.

I did consider using an older version to get this to work, but then I end up unable to use `kindSortOrder`, `navigationLinks` and `sidebarLinks` and I can't find a combination of versions for this plugin and TypeDoc where everything work correctly…

**Comment by GerkinDev** [comment]
Confirmed, a fix is in progress.

**Comment by GerkinDev** [comment]
Indeed, this export was removed since 0.23.16. Update PR is open

**Comment by GerkinDev** [comment]
Please try out the version 0.23.2 and tell me if it works ! Cheers !

**Comment by shawninder** [comment]
Yes, everything is back to normal and I can now have the sidebar and navigation links as well as working code blocks!

Thank you very much for this :)
