### ISSUE TITLE
"Virtual" pages always selected?

### ISSUE THREAD

**Issue by benjie** [KnodesCommunity/typedoc-plugins#55]
Excellent work on these plugins! I'm just getting started with `typedoc` and these plugins really make the generated documentation feel "fuller".

---

You can see the above issue in the documentation itself, e.g. visit the following page:

https://knodescommunity.github.io/typedoc-plugins/_knodes_typedoc_plugin_pages/pages/options.html

Notice that the `Changelog` renders as if it is selected even though it is not:

![Screenshot_20220509_111947](https://user-images.githubusercontent.com/129910/167390827-3dbc8707-31cb-4560-9db6-602f9562ffce.png)

**Comment by benjie** [comment]
No this is just me misinterpretting the style of these nodes - sorry for the noise.

**Comment by GerkinDev** [comment]
Hey there,

Well, the black bar at the left of pages is just the marker for pages. It is used to differentiate from this plugin's nodes and the standard Typedoc ones.

You can totally customize it by adding custom stylesheets. You can check out https://github.com/KnodesCommunity/typedoc-plugins/blob/7aa6ccd67ce2aa3f4e6d490d3ea0256c8f2abfa5/packages/plugin-pages/static/pages.css for reference.

No problem for the noise, that's cool to see there are people using those packages ;)

Cheers !
