### ISSUE TITLE
`lodash` is declared as a peer dependency

### ISSUE THREAD

**Issue by FlorianCassayre** [KnodesCommunity/typedoc-plugins#99]
The installation documentation of e.g. the `typedoc-plugin-pages` package says:
```
npm install --save-dev @knodes/typedoc-plugin-pages typedoc@^0.22.0
```
However this is not sufficient since `lodash` is declared as a peer dependency. This means that if a project does not have `lodash` installed, the plugin will crash.

I am also questioning the motivation behind having `lodash` as a peer dependency, especially for a server-side only module.

In any case, thanks for the great plugins.

**Comment by GerkinDev** [comment]
Indeed. I'm working on a new iteration, during which I'll fix this. Thank you

**Comment by FlorianCassayre** [comment]
Excellent, thanks for the quick response.
